### ISSUE TITLE
Node features

### ISSUE THREAD

**Issue by anandmishra22** [entslscheia/GGNN_Reasoning#1]
Why is number of node features is one greater than number of nodes?

**Comment by entslscheia** [comment]
Hi,

In fact, it's just an implementation issue. The only reason for this implementation is that I want to visit each node with its id directly, and the id of each node starts from 1 instead of 0. 
This really doesn't matter. Of course, you can specify the number of node features to be the same as the number of nodes.

**Comment by entslscheia** [comment]
> Why is number of node features is one greater than number of nodes?

Hi,

In fact, it's just an implementation issue. The only reason for this implementation is that I want to visit each node with its id directly, and the id of each node starts from 1 instead of 0.
This really doesn't matter. Of course, you can specify the number of node features to be the same as the number of nodes.
